### ISSUE TITLE
Getting 404 error but it actually works

### ISSUE THREAD

**Issue by Naforcee** [peardropsoftware/torrent2box#1]
The extension works as expected but I get a popup with an "request failed with error code 404", any solution to this? unsure what the cause is,

**Comment by rmuchall** [comment]
Hi there, sorry you're encountering a problem.
I'll need some more information to troubleshoot the issue. Is this occurring on a private or public tracker. If possible can you post an example link where this issue is occurring?
If you wish to communicate this information privately you can email me: rmuchall@protonmail.com
If you are unable to send me an example link then please can you open the chrome dev tools and see if the extension reports any errors when you click on the link?
Thanks.

**Comment by rmuchall** [comment]
Reopening as not yet resolved.
Advised user to check they are running latest version of extension (v0.0.5).

**Comment by rmuchall** [comment]
Fixed with commit 41444a9
